name: EEMODLOADER
version: 0.0.2
description: The EE Server Side Mod Loader
api-version: 1.18
load: STARTUP
author: streepje8
website: https://github.com/streepje8/EEMODLOADER
main: com.streep.EEMODLOADER.core.EEMODLOADER
libraries:
   - org.json:json:20220320
commands:
 version:
  description: Check The Loader Version.
  permission: EEMODLOADER.version
  permission-message: You do not have permission to use this command.
  usage: "/<command>"
 saveitem:
  description: Save an item to file
  permission: EEMODLOADER.saveitem
  permission-message: You do not have permission to use this command.
  usage: "/<command> <itemname>"
 loaditem:
  description: Load an item from a file
  permission: EEMODLOADER.loaditem
  permission-message: You do not have permission to use this command.
  usage: "/<command> <itemname>"
 setrarity:
  description: Set the rarity of an item
  permission: EEMODLOADER.setrarity
  permission-message: You do not have permission to use this command.
  usage: "/<command> <rarity>"
 test:
  description: Test Command
  permission: EEMODLOADER.test
  permission-message: You do not have permission to use this command.
  usage: "/<command>"
permissions:
  EE.Basic:
   description: The Basic EE Loader Permissions
   default: true
   children:
    EEMODLOADER.version: true
  EE.Advanced:
   description: The Advanced EE Loader Permissions
   default: false
   children:
    EEMODLOADER.saveitem: true
    EEMODLOADER.loaditem: true